name: test_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  image: ^4.5.3
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  skeletonizer: ^1.4.3
  google_fonts: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

